version: "3.9"
services:
  ecoapp_db:
    image: mongo:latest
    volumes:
      - ./.docker/mongodb/data/db/:/data/db/
      - ./.docker/mongodb/data/log/:/var/log/mongodb/
    ports:
      - '27017:27017'
    networks:
      - backend
  ecoapp_server:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - '8080:8083'
    depends_on:
      - ecpoapp_db
    environment:
      API_HOST: '0.0.0.0'
      API_PORT: '8083'
      DB_URI: 'mongodb://ecoapp_db:27017'
      DB_NAME: 'eco_un'
    networks:
      - backend

networks:
  backend: